import './globals.css';

import type { Metadata } from 'next';

import { milne, montserrat_arm, jost } from '@/fonts';

import Header from '@/app/ui/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  alternates: {
    languages: {
      'am': '/am',
      'ru': '/ru'
    }
  }
};

type Props = {
  children: React.ReactNode;
  params: {
    lang: string
  }
}

export default function RootLayout({ children, params }: Props) {
  const font = params.lang === 'am' ? montserrat_arm : jost;

  return (
    <html 
      lang={params.lang}
      className={`${font.className} ${milne.variable}`}
    >
      <body className='overflow-hidden'>
        <Header />
        {children}
      </body>
    </html>
  );
}
